### ISSUE TITLE
Facebook login hangs on callback in method SignInManager.ExternalSignInAsync

### ISSUE THREAD

**Issue by sebglow** [Digiman/Custom-ASP.NET-MVC-Identity-2.0#1]
Hi.
When I use your CustomUserStore I'm unable to login via Facebook account.
Facebook accepts me, makes callback redirect but then SignInManager.ExternalSignInAsync hangs with no error.

A very simple ammendment helped in my case. In CustomUserStore:

        public async Task<User> FindAsync(UserLoginInfo login)
        {
            if (login == null)
                throw new ArgumentNullException("login");

            var userLogin =
                await
                    _database.UserLogins.SingleOrDefaultAsync(
                        ul => ul.LoginProvider == login.LoginProvider && ul.ProviderKey == login.ProviderKey);
            // var user = new User(); ---- replace this line with the one below -------------------------------
            User user = null;
            if (userLogin != null)
                user = await _database.Users.FirstOrDefaultAsync(u => u.Id == userLogin.UserId);

            return user;
        }

Hope that this fix would help somebody and that it doesn't break other things :)
Best regards
Seba

**Comment by Digiman** [comment]
Thanks.
I fix the issue.

Next if i have more time to research i update the whole project with new identity library.
